require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false
